### PR TITLE
WiP: Add additional HIP/ROCm interfaces and enums.

### PR DESCRIPTION
**Pull request by txomin13**
**Summary:**

* This PR puts all generated modules into the `lib/hip -> lib/hipfort` subfolder
* It adds the following modules to `lib/hipfort/`
  * hipfort.f, hipfort_hipblas.f, hipfort_hipsparse.f, hipfort_hipfft.f, hipfort_rocblas.f, ... hipfort_rocsolver.f
   * plus additional `_enums.f` etc. functions
   * plus a `hipfort_check` module that contains `(\w+)Check` routines for the above modules.
   * plus a `rocsolver-auxiliary.c` C file that must be compiled and linked when using the 
     `hipfort_rocsolver.f` module.
* It adds an `iso_c_binding_ext` module to `lib/util` that allows to increment `type(c_ptr)` variables by
  an offset.
* It does not use the  modules in `modules-amdgcn` anymore -> Modified `lib/CMakeLists.txt`
* It fixes the installation and test procedure suggested in `./README.md`

**Testing summary:**

(On Radeon VII)

* Extended list of hipblas tests all compile and pass
* rocblas test passes
* vecadd test passes.
* rocfft test cannot be compiled because the original author used a derived `type` (`type(double2)`) to
model complex numbers instead of the intrinsic `complex(c_double_complex)` Fortran type.
`gfortran` does not support the `c_loc` operation in combination with derived types,
i.e. the memcopies between host and device fail to compile.
Switching to `complex(c_double_complex`) and fixing 
the code parts where the components of the complex datatypes are
read fixes the compilation but the `rocfft_destroy_plan` routines causes a segfault
   * The error check in the test does not make sense at all.

### CODE REVIEW

**Comment by gregrodgers** [comment]
Dominic.  This looks really good.   Some of the lines you generate were too long for the default, so I added compiler option -ffree-line-length-512".   Also, you were missing the dim3 struct so I added that.   After that, I was able to build hipfort.   However when testing with GESTS I found out that GESTS expected hipMemGetInfo(x,y) to have c_size_t args, so that is the third change.  It may be that GESTS is wrong and they should be c_ptr.

**Comment by txomin13** [comment]
Greg, the GESTS interfaces are correct. The issue is that the translator by default interprets
all pointer types (such as `size_t*` as device arrays, hence it converts them to `type(c_ptr)`.
I initially developed this tool to convert the math libraries where this behavior made sense.

**Comment by txomin13** [comment]
> Also, you were missing the dim3 struct so I added that

Can we move these manually defined types and routines (such as `hipCheck`) into a different module that is included
by `hip.f`?

**Comment by txomin13** [comment]
Please review the committed hip modules.

I already prepared

./rocblas.f
./rocfft.f
./rocsolver.f
./rocsparse.f
./hipfft.f
./hipsparse.f
./hipblas.f

for the next iteration.

**Comment by pbauman** [comment]
This is looking good @txomin13 thanks! I'm not building any Fortran codes at the moment (this will change I'm sure, but if @gregrodgers is working on GESTS that will be a good test case), so I don't have a real thorough review to offer. I agree with your choice of moving `hipCheck` to a separate place from the rest of the interface; `hipCheck` is something we've added and not part of the HIP API, so it should live somewhere else, IMHO.

My only comment would be that I don't necessarily mind offering a `hipCheck` function (although in the future it might be nice to have it internally use the hipGetErrorString, but that will be a pain because we'll have to mangle strings between Fortran and C), but I just want to make sure that we don't use it internally in the interface. Rather, I think we should just return the error code and let the users decide how they want to handle the error (and maybe they will decide to use `hipCheck`, but maybe not). I think this is currently the case, but I just wanted to double check. Thanks again!

**Comment by txomin13** [comment]
@pbauman Thanks for your feedback. I agree, it is cleaner to have `hip_check.f` outside of `hip.f`. Will move it out.

**Comment by txomin13** [comment]
**Have fun!** 

The modules compile all. However, when building applications and using
auxiliary functions from the `rocsolver` library, we also need to compile `lib/hip/rocsolver-aliases.c` and
link our executable against it. `rocsolver` assumes that these functions are always inlined, i.e.
it does not provide any symbols for them in the library.  (They will fix this in the near future.)

**Comment by txomin13** [comment]
I put all generated modules into the `lib/hip -> lib/hipfort` subfolder.
I do not use the  modules in `modules-amdgcn` at all anymore.

Please review again.

Summary:

* Added the following modules to `lib/hipfort/`
  * hipfort.f, hipfort_hipblas.f, hipfort_hipsparse.f, hipfort_hipfft.f, hipfort_rocblas.f, ... hipfort_rocsolver.f
   * plus additional `_enums.f` etc. functions
   * plus a `hipfort_check` module that contains `(\w+)Check` routines for the above modules.
   * plus a `rocsolver-auxiliary.c` C file that must be compiled and linked when using the 
     `hipfort_rocsolver.f` module.
* Added an `iso_c_binding_ext` module to `lib/util` that allows to increment `type(c_ptr)` variables by
  an offset.

**Testing summary:**

(On Radeon VII)

* Extended list of hipblas tests all compile and pass
* rocblas test passes
* vecadd test passes.
* rocfft test cannot be compiled because the original author used a derived `type` (`type(double2)`) to
model complex numbers instead of the intrinsic `complex(c_double_complex)` Fortran type.
`gfortran` does not support the `c_loc` operation in combination with derived types,
i.e. the memcopies between host and device fail to compile.
Switching to `complex(c_double_complex`) and fixing 
the code parts where the components of the complex datatypes are
read fixes the compilation but the `rocfft_destroy_plan` routines causes a segfault
   * The error check in the test does not make sense at all.

**Pull request merged**
