### PR TITLE
Add package generation to cmake

### PR DESCRIPTION
**Pull request by eidenyoshida**

### CODE REVIEW

**Comment by eidenyoshida** [comment]
Still needs some work. 
Should the default install path be into /opt/rocm/hipfort ?

I'm also getting the warning below
CPackRPM:Warning: CPACK_SET_DESTDIR is set (=ON) while requesting a relocatable package (CPACK_RPM_PACKAGE_RELOCATABLE is set): this is not supported, the package won't be relocatable.

**Comment by saadrahim** [comment]
Yes default path is /opt/rocm/hipfort. We also need to add the argument for changing default path as it will be a particular rocm version eventually.

https://github.com/RadeonOpenCompute/rocm-cmake/issues/37

**Comment by saadrahim** [comment]
Also, standardize the library version string to match the other projects.

**Comment by eidenyoshida** [comment]
> Yes default path is /opt/rocm/hipfort. We also need to add the argument for changing default path as it will be a particular rocm version eventually.
> 
> [RadeonOpenCompute/rocm-cmake#37](https://github.com/RadeonOpenCompute/rocm-cmake/issues/37)

Changing default path can be done by setting HIPFORT_INSTALL_DIR when calling cmake

**Comment by gregrodgers** [comment]
I would like to close this PR because I merged all the content manually.   When I tested "make package"  it correctly made a deb and an rpm.  One can use the -DHIPFORT_INSTALL_DIR=/opt/rocm<VERSION>/hipfort to control where the package generates files.

**Comment by saadrahim** [comment]
Closing this ticket. Do you prefer we push directly to the master branch for future commits like you did for @eidenyoshida's work?

**Pull request closed without merging**
