### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pramenku**
Clearly stated out to set ROCM_PATH to desired location as per need else default will be /opt/rocm

### CODE REVIEW

**Review by txomin13 — COMMENTED** [review]
Will likely not approve these changes because IMO the intention of this
README section is to show a potential user how to test hipfort without
making bigger changes to their OS.
I believe folder `/tmp/hipfort` was used by intention in the guide.

@gregrodgers should comment on this. He wrote this part.

**Comment by pramenku** [comment]
> Will likely not approve these changes because IMO the intention of this
> README section is to show a potential user how to test hipfort without
> making bigger changes to their OS.
> I believe folder `/tmp/hipfort` was used by intention in the guide.
> 
> @gregrodgers should comment on this. He wrote this part.

Thanks.No issue. We can keep as it is. Anyway, we are already saying for ROCm to set explicit environment ROCM_PATH as per desired version.
Let me edit /tmp one.

**Comment by pramenku** [comment]
Done the change. We are good to go.

**Comment by pramenku** [comment]
Other PR was merged with other updates in README. Closing this PR.

**Pull request closed without merging**
