### PR TITLE
Update Makefile.hipfort

### PR DESCRIPTION
**Pull request by pramenku**
Changed to widely used variable ROCM_PATH. HIP_PLATFORM is now "amd" instead of "hcc"
HIP_PLATFORM=${HIP_PLATFORM:-amd}
ROCM_PATH=${ROCM_PATH:-/opt/rocm}

### CODE REVIEW

**Comment by pramenku** [comment]
Needed for http://ontrack-internal.amd.com/browse/SWDEV-265147

**Comment by txomin13** [comment]
Let's wait for the outcome of this discussion: #45 
Changes are pretty much the same.

**Comment by pramenku** [comment]
> Let's wait for the outcome of this discussion: #45
> Changes are pretty much the same.

Agree. Thanks

**Review by txomin13 — CHANGES_REQUESTED** [review]
Please change `CUDA` env var to `CUDA_PATH` as in #45.

**Comment by pramenku** [comment]
> Please change `CUDA` env var to `CUDA_PATH` as in #45.

Done. Thanks.

**Pull request merged**
