### PR TITLE
Documentation changes for Latex formula

### PR DESCRIPTION
**Pull request by samjwu**
closes https://github.com/RadeonOpenCompute/rocm-docs-core/issues/311

[use \newline instead of double backslash for latex](https://github.com/ROCmSoftwarePlatform/hipfort/commit/1f5bc3ab15fc5a30dc41eb0585dbf347cd523f93) 
since gfortran interprets it as single backslash

### CODE REVIEW

**Comment by cgmb** [comment]
This may be a reasonable workaround, but I don't think this closes the rocm-docs-core issue. Why is rocm-docs-core changing these files when it copies them into its working directory?

**Comment by samjwu** [comment]
> This may be a reasonable workaround, but I don't think this closes the rocm-docs-core issue. Why is rocm-docs-core changing these files when it copies them into its working directory?

This is less a rocm-docs-core function and more gfortran function. The workflow here is specific to hipfort:

- gfortran preprocesses the source fortran code, and puts it in the doxygen/input folder
- doxygen reads from doxygen/input via Doxyfile INPUT setting
- rocm-docs-core generates docs as normal

**Comment by cgmb** [comment]
Thanks for the clear description, @samjwu!

> * gfortran preprocesses the source fortran code

What is the purpose of this step? Perhaps you've explained it to me before, but if so, I have forgotten.

**Comment by samjwu** [comment]
> Thanks for the clear description, @samjwu!
> 
> > * gfortran preprocesses the source fortran code
> 
> What is the purpose of this step? Perhaps you've explained it to me before, but if so, I have forgotten.

That step appears to have been done by @Maetveis in https://github.com/ROCmSoftwarePlatform/hipfort/pull/99 because doxygen doesn't seem to correctly parse the source fortran code, even with preprocessing turned on and with upper-case file names as convention

**Review by cgmb — COMMENTED** [review]
The main problem with this solution is that these files are generated from the C API headers. Your fixes will be undone the next time that the hipfort library is updated.

I'm still thinking about how to handle this problem, but I may yet end up merging this PR anyway as a temporary fix.

**Pull request merged**
