### PR TITLE
WiP: Upgrade to ROCm 3.10/4.0, add RAND modules, add Fortran pointer/target interfaces, add docu

### PR DESCRIPTION
**Pull request by txomin13**
~~**NOTE: This PR requires to move from `-std=f2003` to `-std=f2008` in order to enable overloading of
functions where only the assumed rank of an array input argument differs but not the number, name, and order of input arguments!**~~
(Build process tries to determine now if compiler supports F2008.)
(Issue with current ROCm packaging is that we only ship only modules compatible with one gfortran module file format
per OS as we only ship one set of precompiled modules. We should actually build modules compliant to the last N gfortran module file formats.)

**Fixes**

* Add `value` qualifier to `hipStream` and `hipEvent` where needed
* Enum ambiguity issue when rocblas was used with rocsolver
* Various scalar variables are now passed as reference and not anymore
   as `type(c_ptr)`. Therefore, it is not necessary to use `c_loc` and to add a `target` qualifier
    to the declaration of these parameters in Fortran user code. Among these updated interfaces
    are `hipGetDevice` and various interfaces for querying device properties.

**Minor fixes**

* Change copyright date to 2021

**Main contributions:**

* Upgrade all modules to ROCm 3.10.
* Add hiprand and rocrand modules
* Add documentation for most routines.

* HIP Runtime API:
  * Fortran-user-friendly interfaces for malloc and memcpy operations
    * Work with Fortran pointers instead of type(c_ptr); enables easy slicing
    * Add malloc operation where device array is created according to host or device "source" array or "mold" array.
      "source" implies a memcpy, "mold" does not. 
      This mimicks the ALLOCATE intrinsics behaviour: https://www.ibm.com/support/knowledgecenter/SS2MB5_14.1.0/com.ibm.xlf141.bg.doc/language_ref/alloc.html)

* HIP/ROCm Math Libs:
  * Fortran-user-friendly interfaces for malloc and memcpy operations
    * Work with Fortran pointers instead of type(c_ptr); enables easy slicing
    * Add interfaces that take scalar and vector targets for most routines.
    * Add interfaces that take higher-rank tensor target arrays into account for some interfaces
       where it is clear that one argument is a matrix or a tensor with even higher rank.

    * Add rocblas/hipblas auxiliary functions for various datatypes

**Tests**

* Add tests for f2003 and f2008 modules.
   * All f2003 and f2008 tests pass with f2008 modules on MI100
    * All f2003 and f2008 tests pass with f2008 modules on V100 & A100

**Example usage of the upgraded HIP runtime API**:

https://raw.githubusercontent.com/ROCmSoftwarePlatform/hipfort/ef0380082af511dc68e2b1350ce287cc2f617eee/test/vecadd/main.f03

**Another example that uses rocblas and HIP Runtime API**:

https://raw.githubusercontent.com/ROCmSoftwarePlatform/hipfort/ef0380082af511dc68e2b1350ce287cc2f617eee/test/rocblas/saxpy.f03

### CODE REVIEW

**Comment by txomin13** [comment]
This PR generally adds a larger number of new APIs (coming from the upgrade to ROCm 3.10) 
plus more user-friendly additional interfaces for certain APIs such as
hipMalloc and hipMemcpy as well as most Math API.

Main discussion point is if we can switch to f2008 or if this has impact of some projects that strictly require f2003.

**Comment by pbauman** [comment]
How much of a pain would it be to support both? I.e. detect at configure time if compiler supports the f2008 features needed and then guard with pre-processor macros. That would be my preference, but the maintenance burden is a bit bigger.

**Comment by schoonovernumerics** [comment]
Is their a user story that this work is related to ?

**Comment by schoonovernumerics** [comment]
I currently am working on codes that use c_ptr with ISO_C_BINDING. Will I have to overhaul my code again to use Fortran pointers ?

**Comment by txomin13** [comment]
> I currently am working on codes that use c_ptr with ISO_C_BINDING. Will I have to overhaul my code again to use Fortran pointers ?

Not necessarily. This PR supports this option too. The additional interfaces will allow you to write code like this however:
```
use hipfort
use hipfort_check
use hipfort_hipblas
integer, parameter :: N = 10, M = 20
real :: A(N), B(N,M)
real, pointer :: A_d(:) => null(), B_d(:,:) => null()
!
call hipCheck(hipMalloc(A,N))
call hipCheck(hipMalloc(B_d,source=B)) ! implies a (blocking) copy to device
! 
```

Now you have Fortran pointers that you can slice like this `A_d(4:)` or this `B_d(:,5)`. 
You can still use `c_loc` on them whenever you need a `type(c_ptr)`.

It is a little more user-friendly than looking up number of bytes and being required to use `c_loc` for
every HIP API call.

**Comment by txomin13** [comment]
Added develop branch, this PR should be merged into this one.

**Comment by txomin13** [comment]
@pbauman  Added the requested "ifdef" and check at configure time.

**Comment by txomin13** [comment]
@schoonovernumerics  Can you check if this PR closes #36 ?

**Comment by txomin13** [comment]
@pbauman Can you check if this PR closes #7 ?

**Comment by txomin13** [comment]
@schoonovernumerics Can you check if this covers the test automation needs you mention in
#41 ?

**Comment by txomin13** [comment]
@malcolmroberts  Please check if this PR covers #35

**Comment by schoonovernumerics** [comment]
@txomin13 I'll take a look today

**Comment by txomin13** [comment]
As the PR now passes all tests and adds a substantial number of new interfaces, I will merge it into develop.

**Pull request merged**
