### PR TITLE
File/Folder Reorg Changes

### PR DESCRIPTION
**Pull request by arvindcheru**
**File/Folder Reorg Changes Updated**

1. include folder update to include/<component name>/ structure. ex: The files under include folders (__include/<HIPFORT_ARCH>___  moved to (__include/hipfort/<HIPFORT_ARCH>_)
2. Component Private Binary Files moved to libexec/<component name>. ex: Files _gputable.txt, myarchgpu, mygpu, mymcpu_ in bin moved to _libexec/hipfort_
3. Misc Files/Samples moved to share/<component name>. ex: _Makefile.hipfort_ moved to _share/hipfort_
4. _Makefile.hipfort_ and _hipfc_ updated with new include and binary file paths.

**New Structure - Snapshot**

opt
└── rocm
    ├── bin
    │   └── hipfc
    ├── include
    │   └── hipfort
    │       ├── amdgcn
    │       │   ├── hipfort_auxiliary.mod
    │       │   ├── ....
    │       └── nvptx
    │           ├── hipfort_auxiliary.mod
    │           ├── ....
    ├── lib
    │   ├── libhipfort-amdgcn.a
    │   └── libhipfort-nvptx.a
    ├── libexec
    │   └── hipfort
    │       ├── gputable.txt
    │       ├── myarchgpu -> mymcpu
    │       ├── mygpu -> mymcpu
    │       └── mymcpu
    └── share
        ├── doc
        │   └── hipfort
        │       └── LICENSE
        └── hipfort
            └── Makefile.hipfort

### CODE REVIEW

**Comment by arvindcheru** [comment]
Verified hipfc using run all tests (make all-tests-run, make run_all) with default rocmpath and custom install path (/tmp/hipfort example)

**Comment by fluidnumerics-joe** [comment]
Hey @arvindcheru, when you are running all tests, what platforms are you building on and what versions of ROCm are you using ? I'd like to help put together a punch list that we ideally run before updating master.
I think that we need to decide on 
* ROCm versions list
* AMD target architectures
* Nvidia target architectures
* Operating systems

The cross product of these lists should provide a complete set of tests to help us ensure that hipfort is remaining portable with each merge.

**Comment by fluidnumerics-joe** [comment]
@gregrodgers - I see that we are not using branch protection for `master` nor are we requiring passing reviews to get changes into master. I'd be highly in favor of requiring passing reviews to ensure changes to hipfort meet formatting requirements (I don't think we have this documented anywhere) and portability requirements (also not documented, but see above).

**Comment by arvindcheru** [comment]
> 

The changes were verified on ROCM Mainline with AMD 64 packages on GNU/Linux 
the test (make all-tests-run, make run_all) mentioned were following the steps mentioned in README.
https://github.com/ROCmSoftwarePlatform/hipfort#build-and-test-hipfort-from-source
https://github.com/ROCmSoftwarePlatform/hipfort#amd-devices

**Review by domcharrier — APPROVED** [review]

**Pull request merged**
